name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Run tests
      run: npm test
      if: matrix.os == 'ubuntu-latest'
    
    - name: Run integration tests
      run: node test-integration.js
      if: matrix.os == 'ubuntu-latest'
    
    - name: Package extension
      run: |
        npm install -g vsce
        vsce package --no-dependencies
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      with:
        name: knowledgehub-ai-intelligence-vsix
        path: '*.vsix'

  test-extension:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run extension validation
      run: node test-extension.js