name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile and package
      run: |
        npm run compile
        npm install -g vsce
        vsce package --no-dependencies
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./knowledgehub-ai-intelligence-${{ github.event.release.tag_name }}.vsix
        asset_name: knowledgehub-ai-intelligence-${{ github.event.release.tag_name }}.vsix
        asset_content_type: application/octet-stream
    
    - name: Publish to VS Code Marketplace
      if: secrets.VSCE_TOKEN
      run: vsce publish -p ${{ secrets.VSCE_TOKEN }}